language: node_js
services:
  - mysql
  - postgresql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'create database test;' -U postgres
node_js:
  - "12"

after_success: npm run coverage