language: node_js
node_js:
  - "12"

jobs:
  include:
    - script: npm run test-integ-ddb

    - script: npm run test-integ-sqlite

    - services: mysql
      before_script: mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
      script: npm run test-integ-mysql

    - services: postgresql
      before_script: psql -c 'create database test;' -U postgres
      script: npm run test-integ-psql

    - addons:
        mariadb: '10.5'
      before_script:
       - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
       - sudo mysql -e 'drop user if exists travis@localhost;'
       - sudo mysql -e 'create user travis@localhost;'
       - sudo mysql -e "GRANT ALL PRIVILEGES ON db.* TO 'travis'@'localhost'";
       - sudo mysql -e "GRANT ALL ON *.* to travis@localhost;";
      script: npm run test-integ-mariadb

    - services: mongodb
      before_script:
        - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
      script: npm run test-integ-mongodb
after_success: npm run coverage