language: node_js
node_js:
  - "12"

jobs:
  include:
    - script: npm run test-integ-ddb

    - script: npm run test-integ-sqlite

    - services: mysql
      before_install: mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
      script: npm run test-integ-mysql

    - services: postgresql
      before_install: psql -c 'create database test;' -U postgres
      script: npm run test-integ-psql

after_success: npm run coverage